---
- name: Установка зависимостей для добавления репозиториев
  apt:
    name:
      - ca-certificates
      - curl
      - gnupg
    state: present

- name: Импорт GPG-ключа Azul
  apt_key:
    url: https://repos.azul.com/azul-repo.key
    state: present

- name: Добавление репозитория Azul Zulu
  apt_repository:
    repo: "deb https://repos.azul.com/zulu/deb/ stable main"
    state: present
    filename: zulu

- name: Установка Azul Zulu 17 JDK
  apt:
    name: zulu17-jdk
    state: present
    update_cache: yes

- name: Проверка установки Java
  command: java -version
  register: java_version
  changed_when: false

- name: Вывод версии Java
  debug:
    msg: "{{ java_version.stderr }}"
