---
galaxy_info:
  author: Diogen477
  description: Установка SonarQube Scanner CLI
  company: 
  
  license: MIT
  
  min_ansible_version: "2.12"
  
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
        - noble
    - name: Debian
      versions:
        - bullseye
        - bookworm

  galaxy_tags:
    - sonarqube
    - scanner
    - quality
    - analysis
    - code

dependencies: []
