---
- name: Обновление индексов пакетов
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Безопасное обновление системы
  apt:
    upgrade: safe
    cache_valid_time: 3600
  tags: [never, system_update]

- name: Установка базовых пакетов
  apt:
    name:
      - ssh
      - sshpass
      - unzip
      - screen
      - curl
      - wget
      - software-properties-common
      - ca-certificates
      - gnupg
    state: present

- name: Установка графической оболочки и RDP
  apt:
    name:
      - xorg
      - openbox
      - xvfb
      - xrdp
    state: present

- name: Запуск и включение службы xrdp
  service:
    name: xrdp
    state: started
    enabled: yes
