---
galaxy_info:
  author: Diogen477
  description: Установка 1C:Enterprise Development Tools (EDT)
  company: 
  
  license: MIT
  
  min_ansible_version: "2.12"
  
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
        - noble
    - name: Debian
      versions:
        - bullseye
        - bookworm

  galaxy_tags:
    - 1c
    - edt
    - development
    - ide

dependencies:
  - role: java
