---
galaxy_info:
  author: Diogen477
  description: Базовая настройка системы для GitLab Runner
  company: 
  
  license: MIT
  
  min_ansible_version: "2.12"
  
  platforms:
    - name: Ubuntu
      versions:
        - focal    # 20.04
        - jammy    # 22.04
        - noble    # 24.04
    - name: Debian
      versions:
        - bullseye  # 11
        - bookworm  # 12

  galaxy_tags:
    - system
    - base
    - ubuntu
    - debian
    - xrdp

dependencies: []
