---
galaxy_info:
  author: Diogen477
  description: Установка и настройка PostgreSQL для SonarQube
  license: MIT
  min_ansible_version: "2.12"
  platforms:
    - name: Ubuntu
      versions: [focal, jammy, noble]
    - name: Debian
      versions: [bullseye, bookworm]
  galaxy_tags: [postgresql, database, sonarqube]
dependencies:
  - role: common
