---
galaxy_info:
  author: Diogen477
  description: Установка и настройка SonarQube
  license: MIT
  min_ansible_version: "2.12"
  platforms:
    - name: Ubuntu
      versions: [focal, jammy, noble]
    - name: Debian
      versions: [bullseye, bookworm]
  galaxy_tags: [sonarqube, quality, analysis, code]
dependencies:
  - role: common
  - role: postgresql
